# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html

parameters:

  ## arguments for guzzle
  url: http://jlopez.mx/scores/
  key: key
  pass: secret

services:

  ## guzzle http client
  guzzle:
    class: GuzzleHttp\Client

  ## score
  score:
    class: AppBundle\Services\Score
    arguments: ["@guzzle", "%url%", "%key%", "%pass%"]
